# Generated by Django 3.2.13 on 2022-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_installeruser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_installer',
            field=models.BooleanField(default=False),
        ),
    ]
