# Generated by Django 4.1 on 2022-10-13 02:12

import customer_portal.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityRetailers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_name', models.CharField(max_length=255)),
                ('retailer_abn', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstallationImageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_image_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=120)),
                ('job_type', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('retailer_request', models.BooleanField(default=True)),
                ('aircon', models.CharField(blank=True, max_length=120)),
                ('no_of_panels', models.CharField(blank=True, max_length=120)),
                ('solar_panel', models.CharField(blank=True, max_length=120)),
                ('system_size', models.CharField(blank=True, max_length=120)),
                ('inverter', models.CharField(blank=True, max_length=120)),
                ('no_of_battery', models.CharField(blank=True, max_length=120)),
                ('hotwater', models.CharField(blank=True, max_length=120)),
                ('installation_date', models.CharField(blank=True, max_length=120)),
                ('back_panel', models.FileField(blank=True, upload_to=customer_portal.models.upload_file_path)),
                ('front_of_property', models.FileField(blank=True, upload_to=customer_portal.models.upload_file_path)),
                ('switch_board', models.FileField(blank=True, upload_to=customer_portal.models.upload_file_path)),
                ('installer_image', models.FileField(blank=True, upload_to=customer_portal.models.upload_file_path)),
                ('nmi', models.CharField(blank=True, max_length=120)),
                ('property_type', models.CharField(blank=True, max_length=120)),
                ('system_type', models.CharField(blank=True, max_length=120)),
                ('connection_type', models.CharField(blank=True, max_length=120)),
                ('system_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('is_financed', models.BooleanField(default=False)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_amount', models.CharField(blank=True, max_length=120, null=True)),
                ('total_amount_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_sent', models.BooleanField(default=False)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('pv_applied', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_job', to='company.company')),
                ('customer_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_job', to=settings.AUTH_USER_MODEL)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_designer', to='accounts.installeruser')),
                ('electrician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_electrician', to='accounts.installeruser')),
                ('energy_retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_retailer_job', to='customer_portal.electricityretailers')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_finalized_by', to='accounts.installeruser')),
                ('installer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_installer', to='accounts.installeruser')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_processed_by', to='accounts.installeruser')),
            ],
        ),
        migrations.CreateModel(
            name='PanelSerialNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_serial_number', models.CharField(max_length=255)),
                ('psn_image', models.CharField(max_length=255)),
                ('psn_location_latitude', models.CharField(max_length=255)),
                ('psn_location_longitude', models.CharField(max_length=255)),
                ('psn_timestamp', models.CharField(max_length=255)),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_panels_serials', to='customer_portal.jobdetails')),
            ],
        ),
        migrations.CreateModel(
            name='JobEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('edited_model', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_content_old', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_content_new', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_action', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edited_by', to='accounts.installeruser')),
            ],
        ),
        migrations.CreateModel(
            name='InverterSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverter_serial', models.CharField(max_length=120)),
                ('inverter_serial_image', models.FileField(blank=True, upload_to=customer_portal.models.upload_file_path)),
                ('inverter_location_latitude', models.CharField(max_length=255)),
                ('inverter_location_longitude', models.CharField(max_length=255)),
                ('inverter_timestamp', models.CharField(max_length=255)),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_inverter_serial', to='customer_portal.jobdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InverterPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=customer_portal.models.upload_file_path)),
                ('image_desc', models.CharField(max_length=120)),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_inverter', to='customer_portal.jobdetails')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_image_location_latitude', models.CharField(max_length=255)),
                ('installation_image_location_longitude', models.CharField(max_length=255)),
                ('installation_image_timestamp', models.CharField(max_length=255)),
                ('installation_image', models.FileField(blank=True, upload_to=customer_portal.models.upload_file_path)),
                ('installation_image_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_image', to='customer_portal.installationimagename')),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_number_installation_image', to='customer_portal.jobdetails')),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=255)),
                ('file_details', models.CharField(blank=True, max_length=255, null=True)),
                ('to_email', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_file_type', to='company.company')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_file_type', to='customer_portal.electricityretailers')),
            ],
        ),
        migrations.CreateModel(
            name='FileFieldSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type_field', models.CharField(max_length=255)),
                ('uploaded_form_field', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_file_field', to='company.company')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_type_field', to='customer_portal.filetype')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(blank=True, upload_to=customer_portal.models.upload_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_files', to='company.company')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_files', to=settings.AUTH_USER_MODEL)),
                ('file_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_type_file', to='customer_portal.filetype')),
                ('job_number', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_number_files', to='customer_portal.jobdetails')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_files', to='customer_portal.electricityretailers')),
            ],
        ),
        migrations.CreateModel(
            name='CommonCustomerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('file_details', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, upload_to=customer_portal.models.upload_common_file_path)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_common_file_type', to='company.company')),
            ],
        ),
    ]
