# Generated by Django 3.2.13 on 2022-08-12 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_installer'),
        ('customer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_designer', to='accounts.installeruser'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='electrician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_electrician', to='accounts.installeruser'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='installer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_installer', to='accounts.installeruser'),
        ),
    ]
