# Generated by Django 3.2.13 on 2022-08-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0002_auto_20220812_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='pv_applied',
            field=models.BooleanField(default=False),
        ),
    ]
