# Generated by Django 4.1 on 2022-08-17 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_pv_applied'),
        ('customer_portal', '0003_jobdetails_pv_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_processed_by', to='accounts.installeruser'),
        ),
    ]
