# Generated by Django 4.1 on 2022-08-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0005_electricityretailers_alter_filetype_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityretailers',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
