# Generated by Django 4.1 on 2022-08-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0006_electricityretailers_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='to_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
