# Generated by Django 4.1 on 2022-08-24 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0008_jobdetails_energy_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='energy_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_retailer_job', to='customer_portal.electricityretailers'),
        ),
    ]
