# Generated by Django 4.1 on 2022-08-24 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0009_alter_jobdetails_energy_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfiles',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_files', to='customer_portal.electricityretailers'),
        ),
    ]
