# Generated by Django 4.1 on 2022-08-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0010_customerfiles_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='retailer_request',
            field=models.BooleanField(default=True),
        ),
    ]
