# Generated by Django 3.2.13 on 2022-08-09 23:45

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AustraliaAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(default='Australia', max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('address_original_id', models.CharField(max_length=255, unique=True)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to=company.models.upload_file_path)),
                ('company_statues', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_admin', models.ManyToManyField(related_name='company_admin', to='accounts.InstallerUser')),
                ('company_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_creator', to='accounts.installeruser')),
                ('company_customers', models.ManyToManyField(blank=True, related_name='company_customers', to=settings.AUTH_USER_MODEL)),
                ('company_users', models.ManyToManyField(blank=True, related_name='company_member', to='accounts.InstallerUser')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('is_auto_renew', models.BooleanField(default=True)),
                ('canceled_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_id_sub', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='InstallerInvitation',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('invitation_created', models.DateTimeField(auto_now_add=True)),
                ('invitation_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_company', to='company.company')),
            ],
            options={
                'verbose_name': 'InstallerInvitation',
                'verbose_name_plural': 'InstallerInvitation',
            },
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateTimeField()),
                ('billing_period_end', models.DateTimeField()),
                ('invoice_number', models.CharField(max_length=255)),
                ('invoice_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='company.company')),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_id', to='company.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('address_type', models.CharField(choices=[('billing', 'Billing Address'), ('company_address', 'Company Address')], max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='company.company')),
            ],
        ),
    ]
