# Generated by Django 3.2.13 on 2022-08-02 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_australiaaddressmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AustraliaAddressModel',
        ),
    ]
